version: '1'
services:
  wordpress: #Name of first container
    image: wordpress #image
    links:
      - wordpress_db:mysql #Linked to second container with DB
    ports:
      - 8080:80 #Port 80 from the docker container will be linked to port 8080 of the host machine
  wordpress_db: #Name of second container
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Goldsmith1992!
  phpmyadmin:
    image: phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: Goldsmith1992!
